# name: "Environment"
# runs:
#   using: "composite"
#   steps:
#     - uses: actions/checkout@v2
#       with:
#         repository: godotengine/godot
#         ref: ${{env.GODOT_BASE_BRANCH}}

#     - name: Make apt sources.list use the default Ubuntu repositories
#       shell: bash
#       run: |
#         sudo rm -f /etc/apt/sources.list.d/*
#         sudo cp -f misc/ci/sources.list /etc/apt/sources.list
#         sudo apt-get update

#     - name: Configure dependencies
#       shell: bash
#       run: |
#         sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
#           libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

#     - name: Load .scons_cache directory
#       id: linux-editor-cache
#       uses: actions/cache@v2
#       with:
#         path: ${{github.workspace}}/.scons_cache/
#         key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
#         restore-keys: |
#           ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
#           ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
#           ${{github.job}}-${{env.GODOT_BASE_BRANCH}}

#     - name: Set up Python 3.x
#       uses: actions/setup-python@v2
#       with:
#         python-version: "3.x"
#         architecture: "x64"

#     - name: Configuring Python packages
#       shell: bash
#       run: |
#         python -c "import sys; print(sys.version)"
#         python -m pip install scons
#         python --version
#         scons --version

name: "Godot Environment"
description: "Prepare Godot Engine compile environment"
inputs:
  godot_version:
    description: "Godot Version"
    required: true
    default: "3.x"
outputs:
  godot_version:
    description: "Godot Version"
    value: ${{ steps.environment-setup.outputs.godot-version }}
runs:
  using: "composite"
  steps:
    - id: environment-setup
      run: echo "::set-output name=godot-version::$(echo ${{ inputs.godot_version }})"
      shell: bash
