name: "Godot Custom Builds"
description: "Godot Engine Automation Pipeline For Custom Builds"
author: Vinicius Guerrero
inputs:
  godot-version:
    description: "Godot Version"
    required: true
    default: "3.x"
outputs:
  godot-version:
    description: "Godot Version"
    value: ${{ steps.godot-environment.outputs.godot-version }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.godot-version }}.
      shell: bash
    - id: godot-environment
      run: echo "::set-output name=godot-version::$(echo ${{ inputs.godot-version }})"
      shell: bash
    - run: ${{ github.action_path }}/environment.sh
      shell: bash
