name: "Environment Setup"
description: "Godot Engine Automation Pipeline - Environment Setup"
author: Vinicius Guerrero
runs:
  using: "composite"
  steps:
    - name: Make apt sources.list use the default Ubuntu repositories
      run: |
        sudo rm -f /etc/apt/sources.list.d/*
        sudo cp -f misc/ci/sources.list /etc/apt/sources.list
        sudo apt-get update
      shell: bash
branding:
  icon: upload
  color: white
