name: "Environment"
description: "Build Environment"
inputs:
  godot_version:
    description: "Godot Version"
    required: true
    default: "3.x"
outputs:
  godot_path:
    description: "Source Path"
    value: ${{ steps.engine-source-path.outputs.engine-source-path }}
runs:
  using: "composite"
  steps:
    - name: Prepare Compile Environment
      run: |
        sudo apt-get update &&
        sudo apt-get install -y --no-install-recommends curl git python python3-pip python-openssl wget zip unzip mingw-w64 &&
        sudo apt-get -y install build-essential pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm &&
        sudo pip3 install scons &&
        sudo python -c "import sys; print(sys.version)" && sudo python --version && sudo scons --version &&
        sudo wget https://github.com/godotengine/godot/archive/refs/heads/${{ inputs.godot_version }}.zip && 
        sudo unzip ${{ inputs.godot_version }}.zip && cd godot-${{ inputs.godot_version }}
        pwd && ls
      shell: bash
     - id: engine-source-path
      run: echo "::set-output name=engine-source-path::$(echo pwd)"
      shell: bash
