name: "Environment"
description: "Build Environment"
inputs:
  environment:
    description: "Godot Compile Environment"
    required: true
    default: "Linux"
runs:
  using: "composite"
  steps:
    - name: Prepare Environment
      run: |
        if [[ "${{ inputs.environment }}" == "Linux" ]]; then
          pwd && ls && echo ${{ inputs.environment }}
        fi
      shell: bash
