name: "Environment Setup"
description: "Godot Engine Automation Pipeline - Environment Setup"
author: Vinicius Guerrero
runs:
  using: "composite"
  steps:
    - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update

    - name: Configure dependencies
      run: |
        sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
          libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

    - name: Load .scons_cache directory
      id: linux-editor-cache
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/.scons_cache/
        key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons
        python --version
        scons --version
branding:
  icon: upload
  color: white
