name: "Environment Setup"
description: "Godot Engine Automation Pipeline - Environment Setup"
author: Vinicius Guerrero
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: 3.x
    - name: Validate Environment
      run: ls
      shell: bash
branding:
  icon: upload
  color: white
