name: "Environment"
description: "Build Environment"
inputs:
  environment:
    description: "Godot Compile Environment"
    required: true
    default: "Linux"
runs:
  using: "composite"
  steps:
    - name: Prepare Environment
      if: ${{ inputs.environment == "Linux" }}
      run: |
        pwd && ls && echo ${{ inputs.environment }}
      shell: bash
