name: "Environment"
description: "Environment Action"
inputs:
  GODOT_VERSION:
    description: "Godot Version"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  build-args:
    - ${{ inputs.GODOT_VERSION }}
