name: "Export Environment"
description: "Export Environment"
inputs:
  environment:
    description: "Godot Export Environment"
    required: true
    default: "ubuntu-20.04"
  godot_version:
    description: "Godot Version"
    required: true
    default: "3.3.2"
runs:
  using: "composite"
  steps:
    - name: Export Environment
      run: |
        echo -e "\n Build Platform ${{ inputs.environment }} \n" &&
        echo -e "\n android_sdk_path -> ${ANDROID_HOME} \n adb -> ${ANDROID_HOME}/platform-tools \n" &&

        # Environment Variables
        ROOT_PATH="${ROOT_PATH:="/github/home"}" &&
        WORKSPACE_PATH="${WORKSPACE_PATH:="/github/workspace"}" &&
        TRES_PATH=${ROOT_PATH}/.config/godot/editor_settings-3.tres &&
        LINK_GODOT="https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip" &&
        LINK_TEMPLATES="https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz" &&

        wget ${LINK_GODOT} &&
        wget ${LINK_TEMPLATES} &&
        sudo mkdir -p -v $ROOT_PATH/.cache && sudo mkdir -p -v $ROOT_PATH/.config/godot &&
        sudo mkdir -p -v $ROOT_PATH/.local/share/godot/templates/${GODOT_VERSION}.stable &&

        sudo keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 && pwd && ls -l
      shell: bash
