name: "Export Environment"
description: "Export Environment"
inputs:
  environment:
    description: "Godot Export Environment"
    required: true
    default: "ubuntu-20.04"
  godot_version:
    description: "Godot Version"
    required: true
    default: "3.3.2"
runs:
  using: "composite"
  steps:
    - name: Export Environment
      run: chmod +x export_env/export.sh && ./export_env/export.sh
      shell: bash
