name: "Export Environment"
description: "Export Environment"
inputs:
  platform:
    description: "Godot Export Platform"
    required: true
    default: "Linux"
  godot_version:
    description: "Godot Version"
    required: true
    default: "3.3.2"
runs:
  using: "composite"
  steps:
    - name: Export Environment
      run: |
        echo -e "Build Platform ${{inputs.environment}}" &&
        echo -e "android_sdk_path -> ${ANDROID_HOME} \n adb -> ${ANDROID_HOME}/platform-tools" &&        
        chmod +x actions/export_env/export.sh && bash actions/export_env/export.sh ${{inputs.platform}}
      shell: bash
