name: Action_2

on:
  workflow_dispatch:
    workflow_run:
      workflows: ["Action_1"]
      types:
        - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Configuring Python packages
        run: |
          ls && pwd
