name: Custom Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: false
        default: "3.x"

env:
  GODOT_BASE_BRANCH: ${{ github.event.inputs.version }}
  SCONS_CACHE_LIMIT: 4096

jobs:
  linux-editor:
    runs-on: "ubuntu-20.04"
    name: Editor

    steps:
      - uses: actions/checkout@v2
      - id: environment
        uses: vini-guerrero/godot-custom-builds@main
      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons -j2 verbose=yes warnings=all werror=yes platform=linuxbsd tools=yes tests=no target=release_debug production=yes

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: godot.x11.opt.tools.64
      #     path: bin/godot.x11.opt.tools.64
