name: Export Debug
on: [workflow_dispatch]

env:
  GODOT_VERSION: 3.3.2
  PROJECT_NAME: test_game
  EXPORT_MODE: release
  K8S_SECRET_RELEASE_KEYSTORE_BASE64: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_BASE64 }}
  K8S_SECRET_RELEASE_KEYSTORE_USER: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_USER }}
  K8S_SECRET_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_PASSWORD }}
  IOS_ICON_PATH: "https://raw.githubusercontent.com/vini-guerrero/godot-exporter/master/screenshots/Logo.png"
  PROJECT_PATH: game # Local To Repository Folder With Game
  ITCH_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  ITCH_GAME: godot-exporter
  ITCH_USER: andrea-miele

jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # platform: [iOS, Android, Linux, MacOS, Windows, HTML5]
        platform: [Android]
    steps:
      # Checkout Current Repository
      - uses: actions/checkout@v2

      # Export Godot Project
      - name: Export ${{ matrix.platform }} Version
        id: export
        uses: vini-guerrero/godot-exporter/actions/export@dev
        with:
          platform: ${{ matrix.platform }}
      
      # Upload Artifact
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}
          path: ${{ steps.export.outputs.artifact-path }}

      # Upload Settings Used
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}_settings
          path: ${{ steps.export.outputs.export-settings }}
      
      # Publish Platforms
      - name: Publish Platforms
        uses: vini-guerrero/godot-exporter/actions/publish@dev
        with:
          platform: "Itch"
          channel: ${{ matrix.platform }}
          project_path: ${{ steps.export.outputs.artifact-path }}
