name: Engine
# on: [push]
on: [workflow_dispatch]

env:
  GODOT_BRANCH: 3.3
  SCONS_CACHE_LIMIT: 4096
  SCONS_CACHE: ${{github.workspace}}/.scons_cache/

jobs:
  build:
    name: Build Engine
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: [Zylann/godot_voxel, Gramps/GodotSteam]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ${{ matrix.modules }}

      # - uses: vini-guerrero/godot-custom-builds/actions/build@main
      #   with:
      #     godot_branch: ${{ env.GODOT_BRANCH }}

      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: ${{ matrix.platform }}
      #     path: ${{ steps.build.outputs.artifact-path }}
