name: Build Environment
on: [push]
# on: [workflow_dispatch]

env:
  GODOT_VERSION: 3.3.2
  SCONS_CACHE_LIMIT: 4096
  SCONS_CACHE: ${{github.workspace}}/.scons_cache/

jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [Android, Linux]
    steps:
      # Checkout Current Repository
      - uses: actions/checkout@v2

      # Checkout Godot Repository
      # - uses: actions/checkout@v2
      #   with:
      #     repository: godotengine/godot
      #     ref: ${{ env.GODOT_VERSION }}

      # Java Setup For Android Export
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Python Setup For Godot Engine
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      # Setup Godot Export Environment
      - name: Export Environment
        uses: vini-guerrero/godot-custom-builds/actions/export_env@main
        with:
          godot_version: ${{ env.GODOT_VERSION }}
          platform: ${{ matrix.platform }}

      # Upload Artifact
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}
          path: ./build/${{ matrix.platform }}
