name: Build Engine
on: [push]

env:
  GODOT_VERSION: 3.3.2
  SCONS_CACHE_LIMIT: 4096

jobs:
  Export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vini-guerrero/godot-custom-builds/build@main
      - name: Artifacts
        run: pwd && ls
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: godot.x11.opt.tools.64
      #     path: bin/godot.x11.opt.tools.64

      # - name: Load .scons_cache directory
      #   id: linux-editor-cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{github.workspace}}/.scons_cache/
      #     key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
      #     restore-keys: |
      #       ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
      #       ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
      #       ${{github.job}}-${{env.GODOT_BASE_BRANCH}}

      # - name: Compilation
      #   env:
      #     SCONS_CACHE: ${{github.workspace}}/.scons_cache/
      #   run: |
      #     scons -j2 verbose=yes warnings=all werror=yes platform=linuxbsd tools=yes tests=no target=release_debug production=yes
