name: Environment
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: 3.x
      - uses: ./environment
