name: Build Environment
on: [push]
# on: [workflow_dispatch]

env:
  GODOT_BRANCH: 3.x
  SCONS_CACHE_LIMIT: 4096
  SCONS_CACHE: ${{github.workspace}}/.scons_cache/

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Load Cached Android SDK
        id: Export-Cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/root/android-sdk/
          key: ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BRANCH}}

      - uses: vini-guerrero/godot-custom-builds/export_env@main
        with:
          environment: ${{ matrix.os }}
