name: Export
on: [pull_request]

jobs:
  export-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Prepare Environment
        uses: vini-guerrero/godot-custom-builds/.github/workflows/environment
      - name: Export App
        run: echo "Exporting App"
