name: Export Game
on: [push, workflow_dispatch]

env:
  GODOT_VERSION: 3.3.2
  SCONS_CACHE_LIMIT: 4096

jobs:
  Export:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Android]
    steps:
      # Checkout Current Repository
      - uses: actions/checkout@v2

      # Checkout Godot Repository
      # - uses: actions/checkout@v2
      #   with:
      #     repository: godotengine/godot
      #     ref: ${{ env.GODOT_VERSION }}

      # Java Setup For Android Export
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Set Up Android SDK
      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v2.0.6

      - name: Prepare SDK & NDK
        if: ${{ matrix.platform == 'Android' }}
        run: |
          export ANDROID_HOME=/usr/local/lib/android/sdk/
          export PATH=$PATH:$ANDROID_HOME/tools
          export PATH=$PATH:$ANDROID_HOME/platform-tools
          # ls -R /usr/local/lib/android/
          # sudo mkdir -p /root/.android && sudo touch /root/.android/repositories.cfg
          mv /usr/local/lib/android/sdk/ndk-bundle /usr/local/lib/android/sdk/ndk/21.4.7075529
          /usr/local/lib/android/sdk/tools/bin/sdkmanager --sdk_root=/usr/local/lib/android/sdk "platform-tools" "build-tools;30.0.3" "platforms;android-29" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;21.4.7075529"
          sudo chmod -R a+rwx ${ANDROID_HOME}/ndk && sudo chmod -R a+rwx ${ANDROID_HOME}
          sudo chmod +x /usr/local/lib/android/sdk/build-tools/29.0.2/apksigner

      # # Set Up Android NDK
      # - name: Setup Android NDK
      #   uses: nttld/setup-ndk@v1
      #   with:
      #     ndk-version: r21e

      # Python Setup For Godot Engine
      # - name: Set up Python 3.x
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.x"
      #     architecture: "x64"

      # Setup Godot Export Environment
      - name: Export Environment
        uses: vini-guerrero/godot-exporter/actions/export@dev
        with:
          godot_version: ${{ env.GODOT_VERSION }}
          platform: ${{ matrix.platform }}
          export_path: "game"

      # Upload Artifact
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}
          path: ./game/${{ matrix.platform }}.zip
