name: Export Game
on: [push, workflow_dispatch]

env:
  GODOT_VERSION: 3.3.2
  GAME_NAME: test_game
  IOS_ICON_PATH: "https://raw.githubusercontent.com/vini-guerrero/godot-exporter/master/screenshots/Logo.png"
  PROJECT_PATH: game # Local To Repository Folder With Game
  ITCH_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  ITCH_GAME: godot-exporter
  ITCH_USER: andrea-miele

jobs:
  Export:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [iOS]
    steps:
      # Checkout Current Repository
      - uses: actions/checkout@v2

      # - name: Load Engine Cache
      #   id: Engine-Cache
      #   uses: actions/cache@v2
      #   with:
      #    path: /usr/local/bin/godot
      #     key: ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}-${{github.sha}}
      #     restore-keys: |
      #      ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}-${{github.sha}}
      #      ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}
      #      ${{github.job}}-${{env.GODOT_BRANCH}}

      # Setup Godot Export Environment
      - name: Export Environment
        id: export
        uses: vini-guerrero/godot-exporter/actions/export@dev
        with:
          platform: ${{ matrix.platform }}

      # Publish Platforms
      # - name: Publish Platforms
      #   uses: vini-guerrero/godot-exporter/actions/publish@dev
      #   with:
      #     platform: "Itch"
      #     channel: ${{ matrix.platform }}
      #     project_path: ${{ steps.export.outputs.artifact-path }}

      # Upload Artifact
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}
          path: ${{ steps.export.outputs.artifact-path }}

      # Prepare iOS Icons Platforms
      # - name: iOS Icons
      #   id: icons
      #   uses: vini-guerrero/godot-exporter/actions/ios@dev
      #   with:
      #     project_path: game

      # Upload Icons
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: iOS Icons
      #     path: ${{ steps.icons.outputs.icons }}
