name: Export Game
on: [push, workflow_dispatch]

env:
  GODOT_VERSION: 3.3.2
  SCONS_CACHE_LIMIT: 4096

jobs:
  Export:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Android, Linux, MacOS, Windows]
    steps:
      # Checkout Current Repository
      - uses: actions/checkout@v2

      - name: Load Engine Cache
        id: Engine-Cache
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/godot
          key: ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BRANCH}}

      # Setup Godot Export Environment
      - name: Export Environment
        uses: vini-guerrero/godot-exporter/actions/export@dev
        with:
          godot_version: ${{ env.GODOT_VERSION }}
          platform: ${{ matrix.platform }}
          export_path: "game"

      # Upload Artifact
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}
          path: ./game/${{ matrix.platform }}.zip
