name: Export
on: [push]

jobs:
  export-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Prepare Environment
        uses: ../.github/actions/environment
      - name: Export App
        run: echo "Exporting App"
