name: Export Publish
on: [workflow_dispatch]

env:
  GODOT_VERSION: 3.3.2
  PROJECT_NAME: test_game
  EXPORT_MODE: release
  IOS_ICON_PATH: "https://raw.githubusercontent.com/vini-guerrero/godot-exporter/master/screenshots/Logo.png"
  PROJECT_PATH: game # Local To Repository Folder With Game
  ITCH_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  ITCH_GAME: godot-exporter
  ITCH_USER: andrea-miele

jobs:
  export_publish:
    name: Export
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # platform: [iOS, Android, Linux, MacOS, Windows, HTML5]
        platform: [Android]
    steps:
      # Checkout Current Repository
      - uses: actions/checkout@v2

      # Export Godot Project
      - name: Export ${{ matrix.platform }} Version
        id: export
        uses: vini-guerrero/godot-exporter/actions/export@dev
        with:
          platform: ${{ matrix.platform }}

      # Publish Platforms
#       - name: Publish Platforms
#         uses: vini-guerrero/godot-exporter/actions/publish@dev
#         with:
#           platform: "Itch"
#           channel: ${{ matrix.platform }}
#           project_path: ${{ steps.export.outputs.artifact-path }}

      # Upload Settings Used
#       - uses: actions/upload-artifact@v1
#         with:
#           name: ${{ matrix.platform }}_settings
#           path: ${{ steps.export.outputs.export-settings }}

      # Upload Artifact
#       - uses: actions/upload-artifact@v1
#         with:
#           name: ${{ matrix.platform }}
#           path: ${{ steps.export.outputs.artifact-path }}

#   xcode_build:
#     name: XCode Build
#     runs-on: macOS-latest
#     needs: export_publish
#     steps:
#       - name: Get Exported Artifacts
#         uses: actions/download-artifact@v2
#         with:
#           name: iOS
#       - name: Export Result
#         shell: bash
#         run: |
#           pwd && ls -l &&
#           xcodebuild clean test -project ${GAME_NAME}.xcodeproj -scheme ${GAME_NAME} -destination "platform=iOS Simulator,OS=12.2,name=iPhone X" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO &&
#           pwd && ls -l
