name: Test Action
on: [push]

env:
  GODOT_VERSION: 3.3.2
  SCONS_CACHE_LIMIT: 4096

jobs:
  Editor:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: vini-guerrero/godot-custom-builds/editor@main
        with:
          godot_version: ${{ env.GODOT_VERSION }}
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python --version
          scons --version
