name: Test Action
on: [push]

env:
  GODOT_VERSION: 3.3.2
  SCONS_CACHE_LIMIT: 4096

jobs:
  Editor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vini-guerrero/godot-custom-builds/editor@main
