name: Test Action
on: [push]

env:
  GODOT_BRANCH: 3.x
  SCONS_CACHE_LIMIT: 4096
  SCONS_CACHE: ${{github.workspace}}/.scons_cache/

jobs:
  Editor:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Load .scons_cache directory
        id: Editor-Cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BRANCH}}

      - uses: vini-guerrero/godot-custom-builds/environment@main
        with:
          godot_version: ${{ env.GODOT_BRANCH }}
          custom_module: https://github.com/Zylann/godot_voxel.git
